feat: implement tiling
hei-school/geo-tiler pull request #13
Opened 2024-01-11 13:23 UTC by Dinasoa

2024-01-11 14:39 UTC, hei-teacher requested changes

2024-01-11 14:39 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/endpoint/rest/controller/ZoneTilingController.java
> +  public List<Parcel> getZTJParcel(@RequestParam(required = true, name = "id") String jobId) {
Parcels, plural

2024-01-11 14:39 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/endpoint/rest/controller/mapper/ZoneTilingJobMapper.java
> +  public Status statusConverter(JobStatus jobStatus) {
Use a separate Mapper ?

2024-01-11 14:39 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/endpoint/rest/controller/mapper/ZoneTilingTaskMapper.java
> +            model.getTiles() != null ? model.getTiles().stream().map(this::toRest).toList() : null)
Use a... MONAD 🔥🔥🔥 

ofNullable(model.getTiles())
  .get(tiles -> .stream().map(this::toRest).toList())
  .orElse(null);
  
  Where ofNullable is statically imported from the Optional monad (ilay classe optional eh)

2024-01-11 14:39 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/endpoint/rest/controller/mapper/ZoneTilingTaskMapper.java
> +            zoneTilingJob.getStatus() != null
Optional monad

2024-01-11 14:39 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/endpoint/rest/controller/ZoneTilingJobControllerIT.java
> +                .health(Status.HealthEnum.UNKNOWN)
static import?

2024-01-11 14:39 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/endpoint/rest/controller/ZoneTilingJobControllerIT.java
> +                .progression(Status.ProgressionEnum.PROCESSING))
static import?

2024-01-11 14:39 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedServiceIT.java
> +    List<school.hei.geotiler.endpoint.rest.model.Parcel> actual = zoneTilingController.getZTJParcel(jobId);
Need a more seldom use of empty lines in this then-section

2024-01-11 14:40 UTC, hei-teacher requested changes

2024-01-11 14:40 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedServiceIT.java
> +            .progression(Status.ProgressionEnum.FINISHED)
static import

2024-01-11 14:40 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedServiceIT.java
> +            .health(Status.HealthEnum.SUCCEEDED));
static import

2024-01-12 06:59 UTC, Dinasoa commented on src/test/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedServiceIT.java
> +    assertEquals(school.hei.geotiler.repository.model.Status.ProgressionStatus.FINISHED, changedToFinished.getNewJob().getStatus().getProgression());
I didn't use static import here because there is already a FINISHED static import defined in the scope

2024-01-15 10:47 UTC, hei-teacher approved these changes

2024-01-15 10:48 UTC, merged