chore: integrate geo-tiler api
hei-school/geo-tiler pull request #5
Opened 2023-12-15 16:54 UTC by Mahefaa

2023-12-15 19:34 UTC, bp-lou requested changes

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +  private final int ZOOM_SIZE = 10;
No. Zoom has to be part of parcel. Let's define Parcel as a small geographic area that possesses a fully-defined tiling configuration.

Later on, we will link Parcel with the corresponding tiles numbers in S3.

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    CloseableHttpClient httpClient = HttpClients.createDefault();
Not sure from which dependecy this Apache clients was taken. But I am pretty sure Spring RestTemplate is more powerful, and is more coherent with our Spring technologies.

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    builder.setContentType(ContentType.MULTIPART_FORM_DATA);
static import

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +        ContentType.APPLICATION_JSON,
static import

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      CloseableHttpResponse response = httpClient.execute(uploadFile);
if it's closeable, then use try-with-closeable-resources

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    String service = parcel.getGeoServerParameter().getService();
var geoServerParameter to avoid dereferecing it thousand of times

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    serverInfo.put("concurrency", 8);
No! Just 1. If I'm not mistaken, concurrency was completely disabled on the downloader as AWS lambda did not provide support for the concurrency library needed.

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      e.printStackTrace();
Gosh no.

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    Path geojsonPath = Path.of("/tmp/file.geojson");
Why not use a constant as it is referenced at two different places?

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      e.printStackTrace();
Tompo ô

2023-12-15 19:34 UTC, bp-lou commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      System.out.println("JSON file created successfully at: " + geojsonPath);
This PR is not serious

2023-12-15 19:34 UTC, bp-lou commented on src/test/java/school/hei/geotiler/api/TilesDownloaderApiTest.java
> +
what is the meaning of this empty line

2023-12-20 11:16 UTC, hei-teacher requested changes

2023-12-20 11:16 UTC, hei-teacher commented on src/test/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedServiceTest.java
> +  @SneakyThrows
Why? seems useless

2023-12-20 11:23 UTC, hei-teacher requested changes

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +  public byte[] downloadTiles(Parcel parcel) throws JsonProcessingException {
Why do you force your consumer to handle JsonProcessingException?

I don't like it. Handle it yourself.

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +
useless empty line

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(geoTilesDownloaderApiURl)
is only used at three instrucitons later. Do not define it this early! Put it closer to where it is used

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    FileSystemResource server = new FileSystemResource(getServerInfoFile(parcel));
can be inlined

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    FileSystemResource geojson = getGeojson(parcel);
can be inlined

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +//  {"type": "Polygon", "type": "Feature", "geometry":{"type":"Polygon", "coordinates": []}, "type":"FeatureCollection", "features":[]}
what is this?

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    log.info("GEOJSON: {}", om.writeValueAsString(featureCollection));
If I see in my logs "GEOJSON: blabla", I have no idea for what this geojson is used for. Is it an input? If yes for who? An output? If yes, from who?

2023-12-20 11:23 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/event/ZoneTilingTaskCreatedService.java
> +    } catch (JsonProcessingException e) {
Nah. It's not the responsibility of the consumer to handle such details.

2023-12-20 11:33 UTC, Dinasoa commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    log.info("GEOJSON: {}", om.writeValueAsString(featureCollection));
I used this log to debug the code XD

2023-12-20 11:54 UTC, hei-teacher requested changes

2023-12-20 11:54 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +//    Request body: form-data (server: all parcel server info, geojson: parcel.feature as geojson)
what are these comments for?

2023-12-20 11:54 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    RestTemplate restTemplate = new RestTemplate();
well... divide this section in three parts. The standard given/when/then

given the resquest...

when firing...

then we get...

group your instructions in these 3 blocks. Do not create one million empty new lines like this, as if the function had no structure at all

2023-12-20 11:54 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +
Why this empty new line? you should really pay attention to those empty new lines!

If you put too much empty lines, it gives the feeling that your code has no structure and is just a collection of on million separate/unliked instructions.

Empty lines are indeed very useful when you want to separate mupltiple blocks/parts of your code. But it feels to me you are not using thme in for that purpose!

2023-12-20 11:54 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      e.printStackTrace();
@Mahefaa Didn't you explain why this is bad?

2023-12-20 12:06 UTC, Mahefaa commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +      e.printStackTrace();
the printStackTrace or the objectMapper.writeValue ?

(Consider the creation of a new Instance of ObjectMapper as resolved)

2023-12-20 12:42 UTC, hei-teacher approved these changes

2023-12-20 12:43 UTC, merged