chore: send email to email receiver when tasks are finished successfully
hei-school/geo-tiler pull request #7
Opened 2023-12-20 13:24 UTC by Dinasoa

2023-12-20 13:59 UTC, hei-teacher requested changes

2023-12-20 13:59 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/service/ZoneTilingTaskService.java
> +  public static final String EMAIL_OBJECT = "Resultat du traitement de zone";
Why "Traitement de zone" while the name of the class is ZoneTiling, not ZoneTreatment? Be precise!

Also, Resultat --> Résultat

2023-12-20 14:01 UTC, hei-teacher requested changes

2023-12-20 14:01 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/utils/HTMLUtils.java
> +public class HTMLUtils {
Never ever use Utils againa. @Mahefaa > Explain her

2023-12-20 14:01 UTC, hei-teacher commented on src/main/java/school/hei/geotiler/utils/HTMLUtils.java
> +    ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();
Use var when the type is already explicited by new

2023-12-21 08:30 UTC, Dinasoa commented on src/main/java/school/hei/geotiler/utils/HTMLUtils.java
> +public class HTMLUtils {
Waiting for his explaination

2024-01-02 10:46 UTC, Mahefaa requested changes
don't forget to format your code

2024-01-02 10:46 UTC, Mahefaa commented on src/main/resources/templates/zone_tiling.html
> +        Le pavage de la zone: [[${zone}]] a été effectuée avec succes.
succès

2024-01-02 10:46 UTC, Mahefaa commented on src/main/java/school/hei/geotiler/service/ZoneTilingTaskService.java
> +      }
these actions do not belong here

2024-01-02 12:08 UTC, Mahefaa requested changes

2024-01-02 12:08 UTC, Mahefaa commented on src/main/java/school/hei/geotiler/service/EmailService.java
> +    String emailBody = htmlTemplateParser.apply(ZONE_TILING_TEMPLATE_NAME,context);
missing space between the two function args ( separate first arg + comma from second arg)

2024-01-02 12:11 UTC, Mahefaa requested changes

2024-01-02 12:11 UTC, Mahefaa commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
>      return responseEntity.getBody();
check the statusCode of the response and throw ApiException(ServerException) if not 200

2024-01-03 11:03 UTC, Mahefaa requested changes

2024-01-03 11:03 UTC, Mahefaa commented on src/main/java/school/hei/geotiler/service/api/TilesDownloaderApi.java
> +    }
complex if else

2024-01-04 08:16 UTC, hei-teacher approved these changes

2024-01-04 08:18 UTC, Mahefaa approved these changes
LGTM

2024-01-04 10:26 UTC, merged